owner: displayblox
repo: status
sites:
  - name: Website
    url: https://displayblox.com
  - name: Commute API
    url: https://commuteapi.com/healthcheck
assignees:
  - fcjr
status-website:
  cname: status.leftshift.com
  logoUrl: https://displayblox.com/static/img/logo.png
  favicon: https://displayblox.com/favicon.ico
  name: DisplayBlox Status
  logoHref: https://displayblox.com